name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
     - run: mvn clean package -DskipTests
     - uses: actions/upload-artifact@v2
       with:
        name: artifacts
        path: deployment

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: artifacts
          path: deployment  
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: deployment/ .
          load: true
          tags: automation-image:latest
      -
        name: Inspect
        run: |
          docker image inspect automation-image:latest      
