name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
     - run: mvn clean package -DskipTests
     - uses: actions/upload-artifact@v2
       with:
        name: artifacts
        path: deployment
